config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'posts#index'

  get '/posts' => 'posts#index'

  get '/posts/new' => 'posts#new'

  post '/posts' => 'posts#create'

  get '/posts/:id' => 'posts#show', as: :post

  get '/posts/:id/edit' => 'posts#edit', as: :edit_post

  patch '/posts/:id' => 'posts#update'

  delete '/posts/:id' => 'posts#destroy'

  post '/posts/:id' => 'posts#update_like', as: :update_like

  post '/comments/:id/comment' => 'comments#create_comment', as: :comments

  delete '/comments/:id' => 'comments#delete_comment', as: :delete_comments


end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
   has_many :posts
   has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
def create_comment
		@post = Post.find(params[:id])
		@comment = Comment.new
		@user = User.new
		@comment.post_id = @post.id
		@comment.user_id = current_user.id
		@comment.content = params[:comment][:content]
		@comment.save
		redirect_to post_path(@post)
	end

	def delete_comment
		@comment = Comment.find(params[:id])
		post_id = @comment.post_id
		@comment.destroy
		redirect_to post_path(post_id)
	end 

	private

	def comment_param
		params.require(:comment).permit(:content, :post_id, :user_id)
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_action :authenticate_user!, except: [:index, :show] 

	def index
		@posts = Post.all.order("created_at DESC")
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)
		@post.like = 0
		@post.user_id = current_user.id
		if @post.save
			redirect_to post_path(@post)
		else
			render 'new'
		end
	end

	def show
		@post = Post.find(params[:id])
		@comment = Comment.new
		@user = User.new
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])
		if @post.update(post_params)
			redirect_to root_path
		else
			render 'edit'
		end
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy
		redirect_to root_path
	end

	def update_like
		@post = Post.find(params[:id])
		@post.like += 1
		@post.save
		redirect_to root_path	
	end


	private

	def post_params
		params.require(:post).permit(:title, :body, :user_id)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Facebook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="container">
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<% if user_signed_in? %>
<p>Hi:<%= current_user.email %> </p>
<%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
<% else %>
<%= link_to 'Sign In', new_user_session_path %>
<%= link_to 'Sign Up', new_user_registration_path %>
<% end %>
<%= yield %>

</body>
</html>

app/views/posts/edit.html.erb
<%= form_for @post do |f| %>
<%= f.label :title %><br>
<%= f.text_field :title %><br>
<%= f.label :body %><br>
<%= f.text_area :body %><br>
<%= f.submit %><br>
<%end%>
<%= link_to 'Back', post_path, class:"btn btn-success" %>

app/views/posts/index.html.erb
<%= link_to 'New Post', posts_new_path,class:"btn btn-primary" %>
<div class="row">
 	<% @posts.each do |post| %>
        <div class="col-xs-6 col-md-3">
            <div class="thumbnail">
		            <div class="embed-responsive embed-responsive-4by3">
				            <p><h5>Title</h5></p>
				            <p class="p"><h3><%= link_to post.title, post_path(post) %></h3></p>
				            <p>By: </p>
				            <p></p>
				            <h5><%= post.user.email %></h5>
		            </div>

		            <div class="caption">
		            <p class="date">
				            	Submitted <%= time_ago_in_words(post.created_at)%>Ago
				            </p>
		                <p><%= post.like %></p>
		                <p><%= button_to 'Like' ,update_like_path(post) %> </p>
		                <p><%= post.comments.count %><%= link_to 'Comments', post_path(post)%></p>
		        	</div>
            </div>
            
        </div>

    <% end %>
</div>

app/views/posts/new.html.erb
<%= form_for @post do |f| %>
<%= f.label :title %><br>
<%= f.text_field :title %><br>
<%= f.label :body %><br>
<%= f.text_area :body %><br>
<%= f.submit %><br>
<%end%>
<%= link_to 'Back', root_path, class:"btn btn-success" %>

app/views/posts/show.html.erb
<% if current_user == @post.user %>
			    <td><%= link_to 'Edit', edit_post_path(@post), class:"btn btn-warning" %></td>
			    <td><%= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: "Are you sure?"}, class:"btn btn-danger" %></td>
<% end %>
			    <table class="table table-striped table-hover">
			  <tr>
			    <td>Title</td>
			    <td>Content</td> 
			  </tr>
			  
			  <tr>
			    <td><%= @post.title %></td>
			    <td><%= @post.body %></td> 
			    
			  </tr>	
</table>
<%= link_to 'Back', root_path, class:"btn btn-success" %>


<%= form_for @comment do |f| %>
	<%= f.text_field :content %>
	<%= f.submit "Comment" %> 
<% end %>



<table class="table table-striped table-hover">
			  <tr>
			    <td>Content</td>
			    <td></td>
			    <td>User</td>
			  </tr>
			  <% @post.comments.each do |c| %>
				  <tr>
				    <td><%= c.content %></td>
				    <td><p class="date">
					            	Submitted <%= time_ago_in_words(c.created_at)%>Ago
					            </p></td>
				    <td><%= c.user.email %></td>
				    <% if current_user.id == c.user_id %>
				    	
				    	<td><%= link_to 'Delete',delete_comments_path(c), method: :delete, data: {confirm: "sure?"} %></td>
				    
				    <%end%>
			  </tr>
			  <%end%>
			
</table>